# Generated by Django 3.0.3 on 2020-02-23 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200224_0025'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='order.OrderItem', verbose_name='Barang'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Selesai'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sums',
            field=models.BooleanField(default=False, verbose_name='Dimasukan ke tabungan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weigth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Berat barang'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Barang'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.25)], verbose_name='Berat barang'),
        ),
    ]
