# Generated by Django 2.2.5 on 2019-10-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191016_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasabah',
            name='balance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
