# Generated by Django 2.2.5 on 2019-10-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nasabah_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasabah',
            name='addres',
            field=models.TextField(blank=True, max_length=126, null=True),
        ),
    ]
