# Generated by Django 2.2.5 on 2019-10-18 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191018_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.25)]),
        ),
    ]
