# Generated by Django 2.2.5 on 2019-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weigth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
