# Generated by Django 3.0.3 on 2020-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Asia/Jakarta', max_length=64, verbose_name='Waktu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Total berat barang terjual'),
        ),
    ]
