# Generated by Django 2.2.5 on 2019-10-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191018_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='value',
            field=models.FloatField(),
        ),
    ]
