# Generated by Django 2.2.5 on 2019-10-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191018_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasabah',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
