# Generated by Django 3.0.3 on 2020-02-23 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nasabah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasabah',
            name='addres',
            field=models.TextField(blank=True, max_length=126, null=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='nasabah',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='nasabah',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='nasabah',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
    ]
